### ISSUE TITLE
error "Failed to load external module @babel/register"

### ISSUE THREAD

**Issue by frenkhub** [bdougie/casper-cms-template#6]
I have this error when I launch `npm start` from the command line.

```
[18:32:28] Failed to load external module @babel/register
[18:32:28] Requiring external module babel-register
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (E:\projects\casper-cms-template\node_modules\natives\index.js:143:24)
    at Object.req [as require] (E:\projects\casper-cms-template\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (E:\projects\casper-cms-template\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .js] (E:\projects\casper-cms-template\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\optim\AppData\Roaming\npm-cache\_logs\2020-02-02T17_32_28_448Z-debug.log
```

I'm on windows 10, the npm version is 6.13.7 and the gulp version is 3.9.1 and the gulp cli is 2.2.0.

**Comment by jpmvferreira** [comment]
I have the exact same error trying to build this directly from netlify, the full output is as follows:
```
10:46:35 PM: Build ready to start
10:46:43 PM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
10:46:43 PM: build-image tag: v3.4.1
10:46:43 PM: buildbot version: e1f4178b0d9779ebad1b11d5b54739f82fed3c22
10:46:43 PM: Fetching cached dependencies
10:46:43 PM: Failed to fetch cache, continuing with build
10:46:43 PM: Starting to prepare the repo for build
10:46:44 PM: No cached dependencies found. Cloning fresh repo
10:46:44 PM: git clone https://github.com/JPUnD/casper-cms-template
10:46:44 PM: Preparing Git Reference refs/heads/master
10:46:46 PM: Starting build script
10:46:46 PM: Installing dependencies
10:46:46 PM: Python version set to 2.7
10:46:47 PM: v12.18.0 is already installed.
10:46:47 PM: Now using node v12.18.0 (npm v6.14.4)
10:46:47 PM: Started restoring cached build plugins
10:46:47 PM: Finished restoring cached build plugins
10:46:47 PM: Attempting ruby version 2.7.1, read from environment
10:46:49 PM: Using ruby version 2.7.1
10:46:49 PM: Using PHP version 5.6
10:46:49 PM: 5.2 is already installed.
10:46:49 PM: Using Swift version 5.2
10:46:49 PM: Started restoring cached node modules
10:46:49 PM: Finished restoring cached node modules
10:46:49 PM: Installing NPM modules using NPM version 6.14.4
10:46:50 PM: npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
10:46:50 PM: npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
10:46:51 PM: npm WARN deprecated postcss-cssnext@2.11.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
10:46:51 PM: npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
10:46:52 PM: npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
10:46:54 PM: npm WARN deprecated pkg-resolve@0.1.14: Not maintained anymore.
10:46:56 PM: npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
10:46:56 PM: npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
10:46:57 PM: npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
10:46:57 PM: npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
10:46:57 PM: npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
10:46:57 PM: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
10:46:58 PM: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
10:46:58 PM: npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
10:46:59 PM: npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
10:46:59 PM: npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
10:46:59 PM: npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
10:47:10 PM: > core-js@2.6.11 postinstall /opt/build/repo/node_modules/core-js
10:47:10 PM: > node -e "try{require('./postinstall')}catch(e){}"
10:47:11 PM: npm notice created a lockfile as package-lock.json. You should commit this file.
10:47:11 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
10:47:11 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:47:11 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
10:47:11 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:47:11 PM: npm WARN victor-hugo@1.0.0 No repository field.
10:47:11 PM: added 1137 packages from 804 contributors and audited 1140 packages in 20.932s
10:47:11 PM: 9 packages are looking for funding
10:47:11 PM:   run `npm fund` for details
10:47:11 PM: found 22 vulnerabilities (5 low, 6 moderate, 11 high)
10:47:11 PM:   run `npm audit fix` to fix them, or `npm audit` for details
10:47:11 PM: NPM modules installed
10:47:11 PM: Started restoring cached go cache
10:47:11 PM: Finished restoring cached go cache
10:47:11 PM: go version go1.14.4 linux/amd64
10:47:11 PM: go version go1.14.4 linux/amd64
10:47:11 PM: Installing missing commands
10:47:11 PM: Verify run directory
10:47:12 PM: ​
10:47:12 PM: ┌─────────────────────────────┐
10:47:12 PM: │        Netlify Build        │
10:47:12 PM: └─────────────────────────────┘
10:47:12 PM: ​
10:47:12 PM: ❯ Version
10:47:12 PM:   @netlify/build 3.3.5
10:47:12 PM: ​
10:47:12 PM: ❯ Flags
10:47:12 PM:   deployId: 5f5558bbe700ee1b585ea0fd
10:47:12 PM:   mode: buildbot
10:47:12 PM: ​
10:47:12 PM: ❯ Current directory
10:47:12 PM:   /opt/build/repo
10:47:12 PM: ​
10:47:12 PM: ❯ Config file
10:47:12 PM:   /opt/build/repo/netlify.toml
10:47:12 PM: ​
10:47:12 PM: ❯ Context
10:47:12 PM:   production
10:47:12 PM: ​
10:47:12 PM: ┌────────────────────────────────────┐
10:47:12 PM: │ 1. build.command from netlify.toml │
10:47:12 PM: └────────────────────────────────────┘
10:47:12 PM: ​
10:47:12 PM: $ npm run build
10:47:13 PM: > victor-hugo@1.0.0 build /opt/build/repo
10:47:13 PM: > gulp build
10:47:13 PM: [21:47:13] Failed to load external module @babel/register
10:47:13 PM: [21:47:13] Requiring external module babel-register
10:47:13 PM: fs.js:35
10:47:13 PM: } = primordials;
10:47:13 PM:     ^
10:47:13 PM: ReferenceError: primordials is not defined
10:47:13 PM:     at fs.js:35:5
10:47:13 PM:     at req_ (/opt/build/repo/node_modules/natives/index.js:143:24)
10:47:13 PM:     at Object.req [as require] (/opt/build/repo/node_modules/natives/index.js:55:10)
10:47:13 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
10:47:13 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
10:47:13 PM:     at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
10:47:13 PM:     at Object.require.extensions.<computed> [as .js] (/opt/build/repo/node_modules/babel-register/lib/node.js:152:7)
10:47:13 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
10:47:13 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
10:47:13 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
10:47:13 PM: npm ERR! code ELIFECYCLE
10:47:13 PM: npm ERR! errno 1
10:47:13 PM: npm ERR! victor-hugo@1.0.0 build: `gulp build`
10:47:13 PM: npm ERR! Exit status 1
10:47:13 PM: npm ERR!
10:47:13 PM: npm ERR! Failed at the victor-hugo@1.0.0 build script.
10:47:13 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10:47:13 PM: npm ERR! A complete log of this run can be found in:
10:47:13 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-09-06T21_47_13_752Z-debug.log
10:47:13 PM: ​
10:47:13 PM: ┌─────────────────────────────┐
10:47:13 PM: │   "build.command" failed    │
10:47:13 PM: └─────────────────────────────┘
10:47:13 PM: ​
10:47:13 PM:   Error message
10:47:13 PM:   Command failed with exit code 1: npm run build
10:47:13 PM: ​
10:47:13 PM:   Error location
10:47:13 PM:   In build.command from netlify.toml:
10:47:13 PM:   npm run build
10:47:13 PM: ​
10:47:13 PM:   Resolved config
10:47:13 PM:   build:
10:47:13 PM:     command: npm run build
10:47:13 PM:     commandOrigin: config
10:47:13 PM:     publish: /opt/build/repo/dist
10:47:13 PM: Caching artifacts
10:47:13 PM: Started saving node modules
10:47:13 PM: Finished saving node modules
10:47:13 PM: Started saving build plugins
10:47:13 PM: Finished saving build plugins
10:47:13 PM: Started saving pip cache
10:47:14 PM: Finished saving pip cache
10:47:14 PM: Started saving emacs cask dependencies
10:47:14 PM: Finished saving emacs cask dependencies
10:47:14 PM: Started saving maven dependencies
10:47:14 PM: Finished saving maven dependencies
10:47:14 PM: Started saving boot dependencies
10:47:14 PM: Finished saving boot dependencies
10:47:14 PM: Started saving go dependencies
10:47:14 PM: Finished saving go dependencies
10:47:16 PM: Error running command: Build script returned non-zero exit code: 1
10:47:16 PM: Failing build: Failed to build site
10:47:16 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
10:47:16 PM: Finished processing build request in 32.442961566s
```

**Comment by jpmvferreira** [comment]
According to this [issue report](https://github.com/gulpjs/gulp/issues/1631) the fix is to run `npm i -S babel-register`.

However my lack of knowledge in the matter at hand is extraordinary high, and as such what I did was simply clone to repository locally, run that command, commit to github and wait for netlify to rebuild the website, but nothing changed.

**Comment by jimz-yucolab** [comment]
encountered the same error as the others have mentioned above.
also tried with a clone from the repo, none of the npm scripts work.

**Comment by bdougie** [comment]
#8 fixes this
